import type { RouteDefinition } from './types';

export const borneoLibraryRoute: RouteDefinition = {
  id: 'borneo-library',
  title: 'Borneo Atrium → Library',
  fromNode: 'Borneo Atrium',
  toNode: 'Library',
  scenes: [
    {
        id: 1,
        image: '/images360/L-B-18.jpg',
        label: 'Borneo Atrium Entrance',
        initialYaw: 180,
        forward: { yaw: 225, pitch: -7 },
        instruction: 'You are now at the Borneo Atrium. Follow the arrow to continue toward the escalator.',
    },
    {
        id: 2,
        image: '/images360/L-J-18.jpg',
        label: 'Escalator to Junction Level 1',
        initialYaw: 360,
        forward: { yaw: 360, pitch: 20 },
        back: { yaw: 290, pitch: -12 },
        instruction: 'Go up the escalator to reach Junction Level 1.',
    },
    {
        id: 3,
        image: '/images360/L-J-19.jpg',
        label: 'Junction Balcony',
        initialYaw: 360,
        forward: { yaw: 10, pitch: -12 },
        back: { yaw: 175, pitch: -18 },
        instruction: 'Walk forward along the balcony toward the main walkway.',
    },
    {
        id: 4,
        image: '/images360/L-J-20.jpg',
        label: 'Junction Level 1',
        initialYaw: 90,
        forward: { yaw: 90, pitch: -4 },
        back: { yaw: 180, pitch: -4 },
        instruction: 'You have reached Junction Level 1. Continue ahead to access the library.',
    },
    {
        id: 5,
        image: '/images360/junction-library-1.jpg',
        label: 'Library Main Entrance',
        initialYaw: 180,
        forward: { yaw: 180, pitch: -4 },
        back: { yaw: 0, pitch: -4 },
        instruction: 'You are now at the Library’s main entrance. Enter through the door ahead.',
    },
    {
        id: 6,
        image: '/images360/litojunc3.jpg',
        label: 'Library Lobby – Service Desk Area',
        initialYaw: 120,
        forward: { yaw: 140, pitch: -4 },
        back: { yaw: 350, pitch: -4 },
        instruction: 'This is the library lobby. The service desk is in front of you if you need assistance.',
    },
    {
        id: 7,
        image: '/images360/L-L-3.jpg',
        label: 'Library Interior – Zones Overview',
        initialYaw: 270,
        back: { yaw: 270, pitch: -4 },
        instruction: 'On your left is the Discussion Zone, and on your right is the Quiet Zone.',
    },
  ],
};
