import type { RouteDefinition } from './types';

export const borneoMphRoute: RouteDefinition = {
  id: 'borneo-mph',
  title: 'Borneo Atrium → MPH',
  fromNode: 'Borneo Atrium',
  toNode: 'MPH',
  scenes: [
            {
                id: 1,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
                instruction: 'You have arrived at Borneo Atrium.',
            },
            {
                id: 2,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 175,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
                instruction: 'On your left is the escalator. Go forward to reach the atrium.',
            },
            {
                id: 3,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 175,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 213, pitch: -6 },
                instruction: 'You are almost there. Go straight to the next point.',
            },
            {
                id: 4,
                image: '/images360/L-B-12.jpg',
                label: 'Leisure Zone',
                initialYaw: 250,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 250, pitch: -5 },
                instruction: 'Pass through the leisure zone. Follow the arrow to continue.',
            },
            {
                id: 5,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight and ready turn left',
                initialYaw: 360,
                back : { yaw: 165, pitch: -4 },
                forward : { yaw: 358, pitch: 0 },
                instruction: 'Move forward, then prepare to turn left at the corner.',
            },
            {
                id: 6,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 180,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 175, pitch: -4 },
                instruction: 'Keep going straight until you reach the turn.',
            },
            {
                id: 7,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 90,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 89, pitch: -4 },
                instruction: 'Continue walking in the corridor, the next arrow is slightly to the front.',
            },
            {
                id: 8,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 60,
                back : { yaw: 178, pitch: -5 },
                forward : { yaw: 70, pitch: -6 },
                instruction: 'Go straight along this corridor. Follow the arrow pointing forward.',
            },
            {
                id: 9,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 200,
                forward: { yaw: 190, pitch: -3 },
                back : { yaw: 30, pitch: 0 },
                instruction: 'You are at Block A lobby. Look for the red arrow in front to start the route.',
            },
            {
                id: 10,
                image: '/images360/lobby2.jpg',
                label: 'Outside Block A Lobby',
                initialYaw: 30,
                forward: { yaw: 50, pitch: 0 },
                back: { yaw: 180, pitch: 0 },
                instruction: 'Go straight along the corridor leading to the MPH.',
            },
            {
                id: 11,
                image: '/images360/L-M-7.jpg',
                label: 'Towards MPH',
                initialYaw: 250,
                forward: { yaw: 235, pitch: 0 },
                back: { yaw: 90, pitch: 0 },
                instruction: 'Keep moving forward along this path toward the hall.',
            },
            {
                id: 12,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 0,
                forward: { yaw: 353, pitch: 0 },
                back: { yaw: 190, pitch: -4 },
                instruction: 'Continue straight. You’ll see the entrance ahead soon.',
            },
            {
                id: 13,
                image: '/images360/L-M-13.jpg',
                label: 'Ready to turn right into MPH',
                initialYaw: 360,
                forward: { yaw: 360, pitch: 0 },
                back: { yaw: 175, pitch: -5 },
                instruction: 'Turn right here to enter the multipurpose hall area.',
            },
            {
                id: 14,
                image: '/images360/L-M-16.jpg',
                label: 'Enter the MPH Door',
                initialYaw: 360,
                forward: { yaw: 360, pitch: 0 },
                back: { yaw: 87, pitch: -5 },
                instruction: 'Go straight through the door into the hall lobby.',
            },
            {
                id: 15,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 345,
                forward: { yaw: 340, pitch: 0 },
                back: { yaw: 165, pitch: -4 },
                instruction: 'You’re now inside the MPH lobby. One more step to reach the main hall.',
            },
            {
                id: 16,
                image: '/images360/L-M-18.jpg',
                label: 'You arrived at the MPH! Welcome!',
                initialYaw: 0,
                back: { yaw: 160, pitch: 0 },
                instruction: 'You have arrived at the Multi Purpose Hall. 🎉',
            },
  ],
};
