import type { RouteDefinition } from './types';

export const borneoGblockRoute: RouteDefinition = {
  id: 'borneo-mph',
  title: 'Borneo Atrium → G Block',
  fromNode: 'Borneo Atrium',
  toNode: 'G Block',
  scenes: [
            {
                id: 1,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                forward: { yaw: 190, pitch: -7 },
                instruction: 'You have arrived at Borneo Atrium.',
            },
            {
                id: 2,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 175,
                back : { yaw: 10, pitch: 0 },
                forward : { yaw: 180, pitch: -5 },
                instruction: 'On your left is the escalator. Go forward to reach the atrium.',
            },
            {
                id: 3,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 175,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 213, pitch: -6 },
                instruction: 'You are almost there. Go straight to the next point.',
            },
            {
                id: 4,
                image: '/images360/L-B-12.jpg',
                label: 'Leisure Zone',
                initialYaw: 250,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 250, pitch: -5 },
                instruction: 'Pass through the leisure zone. Follow the arrow to continue.',
            },
            {
                id: 5,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight and ready turn left',
                initialYaw: 360,
                back : { yaw: 165, pitch: -4 },
                forward : { yaw: 358, pitch: 0 },
                instruction: 'Move forward, then prepare to turn left at the corner.',
            },
            {
                id: 6,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 180,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 175, pitch: -4 },
                instruction: 'Keep going straight until you reach the turn.',
            },
            {
                id: 7,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 90,
                back : { yaw: 355, pitch: 0 },
                forward : { yaw: 89, pitch: -4 },
                instruction: 'Continue walking in the corridor, the next arrow is slightly to the front.',
            },
            {
                id: 8,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 60,
                back : { yaw: 178, pitch: -5 },
                forward : { yaw: 70, pitch: -6 },
                instruction: 'Go straight along this corridor. Follow the arrow pointing forward.',
            },
            {
                id: 9,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 250,
                forward: { yaw: 278, pitch: -3 },
                back : { yaw: 30, pitch: 0 },
                instruction: 'You are at Block A lobby. Look for the red arrow in front to start the route.',
            },
            //lobby move to shub
            {
              id: 10,
              image: '/images360/LobbyA_3_Dinign.jpg',
              label: 'Lobby A → G Block Corridor Entrance',
              initialYaw: 175,
              forward: { yaw: 175, pitch: 0 },
              back: { yaw: 5, pitch: 0 },
              instruction: 'Continue straight through the corridor leading toward G Block.',
            },
            {
              id: 11,
              image: '/images360/LobbyA_6_Dinign.jpg',
              label: 'Corridor Midpoint',
              initialYaw: 190,
              forward: { yaw: 215, pitch: 0 },
              back: { yaw: 359, pitch: 0 },
              instruction: 'Continue heading straight toward G Block.',
            },
            {
              id: 12,
              image: '/images360/LobbyA_11_Dinign.jpg',
              label: 'G Block Entrance Door',
              initialYaw: 180,
              forward: { yaw: 170, pitch: 0 },
              back: { yaw: 0, pitch: 0 },
              instruction: 'Go straight and enter through the G Block door.',
            },
            {
              id: 13,
              image: '/images360/LobbyA_12_(BlockG)Dinign.jpg',
              label: 'Inside G Block Lobby',
              initialYaw: 180,
              forward: { yaw: 180, pitch: -3 },
              back: { yaw: 0, pitch: -4 },
              instruction: 'You have entered G Block. The service desk is on your left. Continue walking straight.',
            },
  ],
};
