import type { RouteDefinition } from './types';

export const lobbyBorneoRoute: RouteDefinition = {
  id: 'lobby-borneo',
  title: 'Lobby → Borneo Atrium',
  fromNode: 'Block A Lobby',
  toNode: 'Borneo Atrium',
  scenes: [
            {
            id: 1,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 20,
                forward: { yaw: 30, pitch: 0 },
                instruction: 'You are at Block A lobby. Look for the red arrow in front to start the route.',
            },
            {
                id: 2,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 175,
                forward: { yaw: 178, pitch: -5 },
                back: { yaw: 70, pitch: -6 },
                instruction: 'Go straight along this corridor. Follow the arrow pointing forward.',
            },
            {
                id: 3,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 89, pitch: -4 },
                instruction: 'Continue walking in the corridor, the next arrow is slightly to the front.',
            },
            {
                id: 4,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 175, pitch: -4 },
                instruction: 'Keep going straight until you reach the turn.',
            },
            {
                id: 5,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight and ready turn left',
                initialYaw: 180,
                forward: { yaw: 165, pitch: -4 },
                back: { yaw: 358, pitch: 0 },
                instruction: 'Move forward, then prepare to turn left at the corner.',
            },
            {
                id: 6,
                image: '/images360/L-B-12.jpg',
                label: 'Leisure Zone',
                initialYaw: 10,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 250, pitch: -5 },
                instruction: 'Pass through the leisure zone. Follow the arrow to continue.',
            },
            {
                id: 7,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 355,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 213, pitch: -6 },
                instruction: 'You are almost there. Go straight to the next point.',
            },
            {
                id: 8,
                image: '/images360/L-B-16.jpg',
                label: 'Left side got escalator can go up to Junction',
                initialYaw: 355,
                forward: { yaw: 10, pitch: 0 },
                back: { yaw: 180, pitch: -5 },
                instruction: 'On your left is the escalator. Go forward to reach the atrium.',
            },
            {
                id: 9,
                image: '/images360/L-B-18.jpg',
                label: 'You arrive the Borneo Atrium! Welcome!',
                initialYaw: 180,
                back: { yaw: 190, pitch: -7 },
                instruction: 'You have arrived at Borneo Atrium.',
            },    
  ],
  nextRouteIds: ['borneo-mph', 'borneo-shub', 'borneo-dining', 'borneo-gblock', 'borneo-hq', 'borneo-junction', 'borneo-library'],
};
