import type { RouteDefinition } from './types';

export const lobbyLibraryRoute: RouteDefinition = {
  id: 'lobby-hq',
  title: 'Lobby → Library',
  fromNode: 'Block A Lobby',
  toNode: 'Library',
  scenes: [
    {
      id: 1,
      image: '/images360/lobby_c1.jpg',
      label: 'Block A Lobby',
      initialYaw: 180,
      forward: { yaw: 200, pitch: -9 },
      instruction: 'You are at the Block A lobby. Follow the red arrow to begin your route.',
    },
    {
      id: 2,
      image: '/images360/lobby_c4.jpg',
      label: 'Use Staircase to go Level 1 Library',
      initialYaw: 100,
      forward: { yaw: 110, pitch: 0 },
      back: { yaw: 330, pitch: 0 },
      instruction: 'Go up the staircase ahead to reach the library level.',
    },
    {
      id: 3,
      image: '/images360/library_c5.jpg',
      label: 'Go straight to Library Entrance',
      initialYaw: 360,
      forward: { yaw: 355, pitch: 0 },
      back: { yaw: 180, pitch: -30 },
      instruction: 'Continue straight towards the library entrance.',
    },
    {
      id: 4,
      image: '/images360/library_c7.jpg',
      label: 'Enter with using Student ID if got.',
      initialYaw: 360,
      forward: { yaw: 355, pitch: 0 },
      back: { yaw: 125, pitch: 0 },
      instruction: 'Scan your student ID to enter the library lobby.',
    },
    {
      id: 5,
      image: '/images360/library12.jpg',
      label: 'Library Lobby',
      initialYaw: 30,
      forward: { yaw: 350, pitch: 0 },
      back: { yaw: 65, pitch: 0 },
      instruction: 'You are now inside the library lobby. Proceed forward to the quiet zone.',
    },
    {
      id: 6,
      image: '/images360/library_c9.jpg',
      label: 'Quiet Zone',
      initialYaw: 100,
      forward: { yaw: 180, pitch: 0 },
      back: { yaw: 270, pitch: 0 },
      instruction: 'This is the quiet study zone. Continue ahead to the book section.',
    },
    {
      id: 7,
      image: '/images360/library_c10.jpg',
      label: 'Book Section',
      initialYaw: 80,
      back: { yaw: 180, pitch: 0 },
      instruction: 'You’ve reached the main book section. End of route.',
    },
  ],
  nextRouteIds: ['borneo-mph', 'mph-borneo'],
};