import type { RouteDefinition } from './types';

export const lobbyDiningRoute: RouteDefinition = {
  id: 'lobby-dining',
  title: 'Lobby → Dining Hall',
  fromNode: 'Block A Lobby',
  toNode: 'Dining Hall',
  scenes: [
    {
      id: 1,
      image: '/images360/LobbyA_1_Dining.jpg',
      label: 'A Block Lobby',
      initialYaw: 0,
      forward: { yaw: 330, pitch: 0 },
      instruction: 'You are now at Lobby A. Move forward along the walkway.',
    },
    {
      id: 2,
      image: '/images360/LobbyA_3_Dinign.jpg',
      label: 'Lobby A → G Block Corridor Entrance',
      initialYaw: 175,
      forward: { yaw: 175, pitch: 0 },
      back: { yaw: 70, pitch: 0 },
      instruction: 'Continue straight through the corridor leading toward G Block.',
    },
    {
      id: 3,
      image: '/images360/LobbyA_5_Dinign.jpg',
      label: 'Connecting Corridor',
      initialYaw: 180,
      forward: { yaw: 180, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Keep walking straight along the corridor.',
    },
    {
      id: 4,
      image: '/images360/LobbyA_6_Dinign.jpg',
      label: 'Corridor Midpoint',
      initialYaw: 190,
      forward: { yaw: 185, pitch: 0 },
      back: { yaw: 359, pitch: 0 },
      instruction: 'Continue heading straight toward G Block.',
    },
    {
      id: 5,
      image: '/images360/LobbyA_7_Dinign.jpg',
      label: 'G Block Entrance Ahead',
      initialYaw: 180,
      forward: { yaw: 178, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Turn right here and enter the G Block building.',
    },
    {
      id: 6,
      image: '/images360/LobbyA_11_Dinign.jpg',
      label: 'G Block Entrance Door',
      initialYaw: 180,
      forward: { yaw: 170, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Go straight and enter through the G Block door.',
    },
    {
      id: 7,
      image: '/images360/LobbyA_12_(BlockG)Dinign.jpg',
      label: 'Inside G Block Lobby',
      initialYaw: 180,
      forward: { yaw: 180, pitch: -3 },
      back: { yaw: 0, pitch: -4 },
      instruction: 'You have entered G Block. The service desk is on your left. Continue walking straight.',
    },
    {
      id: 8,
      image: '/images360/LobbyA_15_Dinign.jpg',
      label: 'Walkway Toward Dining Area',
      initialYaw: 180,
      forward: { yaw: 186, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Keep going straight along the walkway.',
    },
    {
      id: 9,
      image: '/images360/LobbyA_16_Dinign.jpg',
      label: 'Convenience Store Area',
      initialYaw: 180,
      forward: { yaw: 170, pitch: 0 },
      back: { yaw: 348, pitch: -4 },
      instruction: 'Continue forward. A convenience store is located on your right side.',
    },
    {
      id: 10,
      image: '/images360/Dining1_StudentHub.jpg',
      label: 'Dining Hall / Student Hub',
      initialYaw: 180,
      back: { yaw: 350, pitch: -2 },
      instruction: 'You have arrived at the Dining Hall.',
    },

  ],
  nextRouteIds: ['borneo-mph', 'mph-borneo'],
};
