import type { RouteDefinition } from './types';

export const lobbyGblockRoute: RouteDefinition = {
  id: 'lobby-gblock',
  title: 'Lobby → G Block',
  fromNode: 'Block A Lobby',
  toNode: 'G Block',
  scenes: [
    {
      id: 1,
      image: '/images360/LobbyA_1_Dining.jpg',
      label: 'A Block Lobby',
      initialYaw: 0,
      forward: { yaw: 330, pitch: 0 },
      instruction: 'You are now at Lobby A. Move forward along the walkway.',
    },
    {
      id: 2,
      image: '/images360/LobbyA_3_Dinign.jpg',
      label: 'Lobby A → G Block Corridor Entrance',
      initialYaw: 175,
      forward: { yaw: 175, pitch: 0 },
      back: { yaw: 70, pitch: 0 },
      instruction: 'Continue straight through the corridor leading toward G Block.',
    },
    {
      id: 3,
      image: '/images360/LobbyA_5_Dinign.jpg',
      label: 'Connecting Corridor',
      initialYaw: 180,
      forward: { yaw: 180, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Keep walking straight along the corridor.',
    },
    {
      id: 4,
      image: '/images360/LobbyA_6_Dinign.jpg',
      label: 'Corridor Midpoint',
      initialYaw: 190,
      forward: { yaw: 185, pitch: 0 },
      back: { yaw: 359, pitch: 0 },
      instruction: 'Continue heading straight toward G Block.',
    },
    {
      id: 5,
      image: '/images360/LobbyA_7_Dinign.jpg',
      label: 'G Block Entrance Ahead',
      initialYaw: 180,
      forward: { yaw: 178, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Turn right here and enter the G Block building.',
    },
    {
      id: 6,
      image: '/images360/LobbyA_11_Dinign.jpg',
      label: 'G Block Entrance Door',
      initialYaw: 180,
      forward: { yaw: 170, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Go straight and enter through the G Block door.',
    },
    {
      id: 7,
      image: '/images360/LobbyA_12_(BlockG)Dinign.jpg',
      label: 'Inside G Block Lobby',
      initialYaw: 180,
      back: { yaw: 0, pitch: -4 },
      instruction: 'You are now inside G Block. The service desk is on your left.',
    },
    {
      id: 8,
      image: '/images360/LobbyA_13_(ServiceDesk)Dinign.jpg',
      label: 'G Block Service Desk',
      initialYaw: 170,
      instruction: 'You have arrived at the service desk.',
    },
  ],
  nextRouteIds: ['borneo-mph', 'mph-borneo'],
};
