// src/app/navigate/route_bank/lobby-mph.ts
import type { RouteDefinition } from './types';

export const lobbyMphRoute: RouteDefinition = {
  id: 'lobby-mph',
  title: 'Lobby → Multi Purpose Hall',
  fromNode: 'Block A Lobby',
  toNode: 'Multi Purpose Hall',
  scenes: [
    {
      id: 1,
      image: '/images360/lobby_c1.jpg',
      label: 'Block A Lobby',
      initialYaw: 0,
      forward: { yaw: 360, pitch: 0 },
      instruction: 'You are at Block A lobby. Look for the red arrow in front to start the route.',
    },
    {
      id: 2,
      image: '/images360/lobby2.jpg',
      label: 'Outside Block A Lobby',
      initialYaw: 30,
      forward: { yaw: 50, pitch: 0 },
      back: { yaw: 180, pitch: 0 },
      instruction: 'Go straight along the corridor leading to the MPH.',
    },
    {
      id: 3,
      image: '/images360/L-M-7.jpg',
      label: 'Towards MPH',
      initialYaw: 250,
      forward: { yaw: 235, pitch: 0 },
      back: { yaw: 90, pitch: 0 },
      instruction: 'Keep moving forward along this path toward the hall.',
    },
    {
      id: 4,
      image: '/images360/L-M-10.jpg',
      label: 'Go Straight',
      initialYaw: 0,
      forward: { yaw: 353, pitch: 0 },
      back: { yaw: 190, pitch: -4 },
      instruction: 'Continue straight. You’ll see the entrance ahead soon.',
    },
    {
      id: 5,
      image: '/images360/L-M-13.jpg',
      label: 'Ready to turn right into MPH',
      initialYaw: 360,
      forward: { yaw: 360, pitch: 0 },
      back: { yaw: 175, pitch: -5 },
      instruction: 'Turn right here to enter the multipurpose hall area.',
    },
    {
      id: 6,
      image: '/images360/L-M-16.jpg',
      label: 'Enter the MPH Door',
      initialYaw: 360,
      forward: { yaw: 360, pitch: 0 },
      back: { yaw: 87, pitch: -5 },
      instruction: 'Go straight through the door into the hall lobby.',
    },
    {
      id: 7,
      image: '/images360/L-M-17.jpg',
      label: 'Multi Purpose Hall Lobby',
      initialYaw: 345,
      forward: { yaw: 340, pitch: 0 },
      back: { yaw: 165, pitch: -4 },
      instruction: 'You’re now inside the MPH lobby. One more step to reach the main hall.',
    },
    {
      id: 8,
      image: '/images360/L-M-18.jpg',
      label: 'You arrived at the MPH! Welcome!',
      initialYaw: 0,
      back: { yaw: 160, pitch: 0 },
      instruction: 'You have arrived at the Multi Purpose Hall. 🎉',
    },
  ],
  nextRouteIds: ['mph-borneo', 'mph-library', 'mph-junction'],
};
