import type { RouteDefinition } from './types';

export const lobbyShubRoute: RouteDefinition = {
  id: 'lobby-shub',
  title: 'Lobby → Student Hub',
  fromNode: 'Block A Lobby',
  toNode: 'Student Hub',
  scenes: [
    {
      id: 1,
      image: '/images360/LobbyA_1_Dining.jpg',
      label: 'A Block Lobby',
      initialYaw: 0,
      forward: { yaw: 330, pitch: 0 },
      instruction: 'You are now at Lobby A. Move forward along the walkway.',
    },
    {
      id: 2,
      image: '/images360/LobbyA_3_Dinign.jpg',
      label: 'Lobby A → G Block Corridor Entrance',
      initialYaw: 175,
      forward: { yaw: 175, pitch: 0 },
      back: { yaw: 70, pitch: 0 },
      instruction: 'Continue straight through the corridor leading toward G Block.',
    },
    {
      id: 3,
      image: '/images360/LobbyA_5_Dinign.jpg',
      label: 'Connecting Corridor',
      initialYaw: 180,
      forward: { yaw: 180, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Keep walking straight along the corridor.',
    },
    {
      id: 4,
      image: '/images360/LobbyA_6_Dinign.jpg',
      label: 'Corridor Midpoint',
      initialYaw: 190,
      forward: { yaw: 185, pitch: 0 },
      back: { yaw: 359, pitch: 0 },
      instruction: 'Continue heading straight toward G Block.',
    },
    {
      id: 5,
      image: '/images360/LobbyA_7_Dinign.jpg',
      label: 'G Block Entrance Ahead',
      initialYaw: 180,
      forward: { yaw: 178, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Turn right here and enter the G Block building.',
    },
    {
      id: 6,
      image: '/images360/LobbyA_11_Dinign.jpg',
      label: 'G Block Entrance Door',
      initialYaw: 180,
      forward: { yaw: 170, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Go straight and enter through the G Block door.',
    },
    {
      id: 7,
      image: '/images360/LobbyA_12_(BlockG)Dinign.jpg',
      label: 'Inside G Block Lobby',
      initialYaw: 180,
      forward: { yaw: 180, pitch: -3 },
      back: { yaw: 0, pitch: -4 },
      instruction: 'You have entered G Block. The service desk is on your left. Continue walking straight.',
    },
    {
      id: 8,
      image: '/images360/LobbyA_15_Dinign.jpg',
      label: 'Walkway Toward Dining Area',
      initialYaw: 180,
      forward: { yaw: 186, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Keep going straight along the walkway.',
    },
    {
      id: 9,
      image: '/images360/Dining2_StudentHub.jpg',
      label: 'Dining Area First Section',
      initialYaw: 180,
      forward: { yaw: 160, pitch: -3 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'You are now entering the dining area. Continue walking straight ahead.',
    },
    {
      id: 10,
      image: '/images360/Dining4_StudentHub.jpg',
      label: 'Dining Area Mid Section',
      initialYaw: 180,
      forward: { yaw: 195, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Keep moving forward through the dining area toward the Student Hub.',
    },
    {
      id: 11,
      image: '/images360/Dining6_StudentHub.jpg',
      label: 'Dining Area',
      initialYaw: 180,
      forward: { yaw: 180, pitch: 0 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'Walk forward and cross the zebra crossing ahead.',
    },
    {
      id: 12,
      image: '/images360/Dining8_StudentHub.jpg',
      label: 'Student Hub Entrance Area',
      initialYaw: 180,
      forward: { yaw: 168, pitch: -3 },
      back: { yaw: 0, pitch: 0 },
      instruction: 'You have reached the Student Hub entrance area. Continue forward to enter the building.',
    },
    {
      id: 13,
      image: '/images360/StudentHub1.jpg',
      label: 'Inside Student Hub',
      initialYaw: 0,
      back: { yaw: 180, pitch: 0 },
      instruction: 'You have entered the Student Hub. Welcome!',
    },
  ],
  nextRouteIds: ['borneo-mph', 'mph-borneo'],
};
