import type { RouteDefinition } from './types';

export const lobbyJunctionRoute: RouteDefinition = {
  id: 'lobby-junction',
  title: 'Lobby → Junction',
  fromNode: 'Block A Lobby',
  toNode: 'Junction',
  scenes: [
    {
      id: 1,
      image: '/images360/L-B-1.jpg',
      label: 'Block A Lobby',
      initialYaw: 20,
      forward: { yaw: 30, pitch: 0 },
      instruction: 'Walk forward toward the corridor entrance. Follow the arrow to move out from the lobby.',
    },
    {
      id: 2,
      image: '/images360/L-B-3.jpg',
      label: 'Block A Groundfloor Toilet',
      initialYaw: 175,
      forward: { yaw: 178, pitch: -5 },
      back: { yaw: 70, pitch: -6 },
      instruction: 'Continue straight through the corridor. Follow the arrow to proceed further down the hallway.',
    },
    {
      id: 3,
      image: '/images360/L-B-6.jpg',
      label: 'Walkway in Corridor',
      initialYaw: 360,
      forward: { yaw: 355, pitch: 0 },
      back: { yaw: 89, pitch: -4 },
      instruction: 'Keep walking along the corridor. Follow the arrow directly in front to continue straight.',
    },
    {
      id: 4,
      image: '/images360/L-B-8.jpg',
      label: 'Walkway in Corridor',
      initialYaw: 360,
      forward: { yaw: 355, pitch: 0 },
      back: { yaw: 175, pitch: -4 },
      instruction: 'Move forward along the hallway. Keep following the straight path ahead.',
    },
    {
      id: 5,
      image: '/images360/L-B-10.jpg',
      label: 'Go Straight and ready turn left',
      initialYaw: 180,
      forward: { yaw: 165, pitch: -4 },
      back: { yaw: 358, pitch: 0 },
      instruction: 'Continue straight and prepare to turn left at the upcoming corner. Follow the arrow to proceed.',
    },
    {
      id: 6,
      image: '/images360/L-B-12.jpg',
      label: 'Leisure Zone',
      initialYaw: 10,
      forward: { yaw: 355, pitch: 0 },
      back: { yaw: 250, pitch: -5 },
      instruction: 'Walk past the Leisure Zone area. Follow the arrow ahead to continue toward the escalator.',
    },
    {
      id: 7,
      image: '/images360/L-B-15.jpg',
      label: 'You are almost there',
      initialYaw: 355,
      forward: { yaw: 355, pitch: -10 },
      back: { yaw: 213, pitch: -6 },
      instruction: 'Continue straight toward the escalator area. You’re getting close follow the arrow forward.',
    },
    {
      id: 8,
      image: '/images360/L-J-16.jpg',
      label: 'Left side got escalator can go up to Junction',
      initialYaw: 325,
      forward: { yaw: 315, pitch: -10 },
      back: { yaw: 180, pitch: -6 },
      instruction: 'Move toward the escalator on the left. Follow the arrow to head up to Junction Level 1.',
    },
    {
      id: 9,
      image: '/images360/L-J-18.jpg',
      label: 'Go up escalator',
      initialYaw: 360,
      forward: { yaw: 360, pitch: 20 },
      back: { yaw: 290, pitch: -12 },
      instruction: 'Head up the escalator to reach Junction Level 1. Follow the arrow upward to continue.',
    },
    {
      id: 10,
      image: '/images360/L-J-19.jpg',
      label: 'Junction Balcony',
      initialYaw: 360,
      forward: { yaw: 10, pitch: -12 },
      back: { yaw: 175, pitch: -18 },
      instruction: 'Continue walking forward along the balcony area. Follow the arrow to approach the main walkway.',
    },
    {
      id: 11,
      image: '/images360/L-J-20.jpg',
      label: 'You arrive Junction Level 1',
      initialYaw: 270,
      back: { yaw: 180, pitch: -4 },
      instruction: 'You’ve reached Junction Level 1. You may continue exploring or select the next route.',
    },
  ],
  nextRouteIds: ['borneo-mph', 'mph-borneo'],
};

