import type { RouteDefinition } from './types';

export const mphLibraryRoute: RouteDefinition = {
  id: 'mph-library',
  title: 'MPH → Library',
  fromNode: 'Multi Purpose Hall',
  toNode: 'Library',
  scenes: [
            {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
                instruction: 'You’re now inside the MPH lobby. One more step to reach the main hall.',
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Enter the MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
                instruction: 'Go straight through the door into the hall lobby.',
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Ready to turn right into MPH',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
                instruction: 'Turn right here to enter the multipurpose hall area.',
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
                instruction: 'Continue straight. You’ll see the entrance ahead soon.',
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Towards MPH',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
                instruction: 'Keep moving forward along this path toward the hall.',
            },
            {
                id: 6,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 352,
                forward: { yaw: 320, pitch: 0 },
                back: { yaw: 190, pitch: -3 },
                instruction: 'You are at Block A lobby. Look for the red arrow in front to start the route.',
            },
            {
                id: 7,
                image: '/images360/lobby_c4.jpg',
                label: 'Use Staircase to go Level 1 Library',
                initialYaw: 100,
                forward: { yaw: 110, pitch: 0 },
                back: { yaw: 330, pitch: 0 },
                instruction: 'Go up the staircase ahead to reach the library level.',
            },
            {
                id: 8,
                image: '/images360/library_c5.jpg',
                label: 'Go straight to Library Entrance',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 180, pitch: -30 },
                instruction: 'Continue straight towards the library entrance.',
            },
            {
                id: 9,
                image: '/images360/library_c7.jpg',
                label: 'Enter with using Student ID if got.',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 125, pitch: 0 },
                instruction: 'Scan your student ID to enter the library lobby.',
            },
            {
                id: 10,
                image: '/images360/library12.jpg',
                label: 'Library Lobby',
                initialYaw: 30,
                forward: { yaw: 350, pitch: 0 },
                back: { yaw: 65, pitch: 0 },
                instruction: 'You are now inside the library lobby. Proceed forward to the quiet zone.',
            },
            {
                id: 11,
                image: '/images360/library_c9.jpg',
                label: 'Quiet Zone',
                initialYaw: 100,
                forward: { yaw: 180, pitch: 0 },
                back: { yaw: 270, pitch: 0 },
                instruction: 'This is the quiet study zone. Continue ahead to the book section.',
            },
            {
                id: 12,
                image: '/images360/library_c10.jpg',
                label: 'Book Section',
                initialYaw: 80,
                back: { yaw: 180, pitch: 0 },
                instruction: 'You’ve reached the main book section. End of route.',
            },
  ],
};
