import type { RouteDefinition } from './types';

export const mphJunctionRoute: RouteDefinition = {
  id: 'mph-junction',
  title: 'MPH → Junction',
  fromNode: 'Multi Purpose Hall',
  toNode: 'Junction',
  scenes: [
            {
                id: 1,
                image: '/images360/L-M-17.jpg',
                label: 'Multi Purpose Hall Lobby',
                initialYaw: 165,
                forward : { yaw: 165, pitch: -4 },
                instruction: 'You’re now inside the MPH lobby. One more step to reach the main hall.',
            },
            {
                id: 2,
                image: '/images360/L-M-16.jpg',
                label: 'Enter the MPH Door',
                initialYaw: 90,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 87, pitch: -5 },
                instruction: 'Go straight through the door into the hall lobby.',
            },
            {
                id: 3,
                image: '/images360/L-M-13.jpg',
                label: 'Ready to turn right into MPH',
                initialYaw: 180,
                back : { yaw: 360, pitch: 0 },
                forward: { yaw: 175, pitch: -5 },
                instruction: 'Turn right here to enter the multipurpose hall area.',
            },
            {
                id: 4,
                image: '/images360/L-M-10.jpg',
                label: 'Go Straight',
                initialYaw: 180,
                back : { yaw: 353, pitch: 0 },
                forward: { yaw: 190, pitch: -4 },
                instruction: 'Continue straight. You’ll see the entrance ahead soon.',
            },
            {
                id: 5,
                image: '/images360/L-M-7.jpg',
                label: 'Towards MPH',
                initialYaw: 70,
                back : { yaw: 235, pitch: 0 },
                forward : { yaw: 90, pitch: 0 },
                instruction: 'Keep moving forward along this path toward the hall.',
            },
            {
                id: 7,
                image: '/images360/L-B-1.jpg',
                label: 'Block A Lobby',
                initialYaw: 20,
                forward: { yaw: 30, pitch: 0 },
                instruction: 'You are at Block A lobby. Look for the red arrow in front to start the route.',
            },
            {
                id: 8,
                image: '/images360/L-B-3.jpg',
                label: 'Block A Groundfloor Toilet',
                initialYaw: 175,
                forward: { yaw: 178, pitch: -5 },
                back: { yaw: 70, pitch: -6 },
                instruction: 'Go straight along this corridor. Follow the arrow pointing forward.',
            },
            {
                id: 9,
                image: '/images360/L-B-6.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 89, pitch: -4 },
                instruction: 'Continue walking in the corridor, the next arrow is slightly to the front.',
            },
            {
                id: 10,
                image: '/images360/L-B-8.jpg',
                label: 'Walkway in Corridor',
                initialYaw: 360,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 175, pitch: -4 },
                instruction: 'Keep going straight until you reach the turn.',
            },
            {
                id: 11,
                image: '/images360/L-B-10.jpg',
                label: 'Go Straight and ready turn left',
                initialYaw: 180,
                forward: { yaw: 165, pitch: -4 },
                back: { yaw: 358, pitch: 0 },
                instruction: 'Move forward, then prepare to turn left at the corner.',
            },
            {
                id: 12,
                image: '/images360/L-B-12.jpg',
                label: 'Leisure Zone',
                initialYaw: 10,
                forward: { yaw: 355, pitch: 0 },
                back: { yaw: 250, pitch: -5 },
                instruction: 'Pass through the leisure zone. Follow the arrow to continue.',
            },
            {
                id: 13,
                image: '/images360/L-B-15.jpg',
                label: 'You are almost there',
                initialYaw: 355,
                forward: { yaw: 330, pitch: 0 },
                back: { yaw: 213, pitch: -6 },
                instruction: 'You are almost there. Go straight to the escalator.',
            },
            {
                id: 14,
                image: '/images360/L-J-18.jpg',
                label: 'Go up escalator',
                initialYaw: 360,
                forward: { yaw: 360, pitch: 20 },
                back: { yaw: 290, pitch: -12 },
                instruction: 'Head up the escalator to reach Junction Level 1. Follow the arrow upward to continue.',
            },
            {
                id: 15,
                image: '/images360/L-J-19.jpg',
                label: 'Junction Balcony',
                initialYaw: 360,
                forward: { yaw: 10, pitch: -12 },
                back: { yaw: 175, pitch: -18 },
                instruction: 'Continue walking forward along the balcony area. Follow the arrow to approach the main walkway.',
            },
            {
                id: 16,
                image: '/images360/L-J-20.jpg',
                label: 'You arrive Junction Level 1',
                initialYaw: 270,
                back: { yaw: 180, pitch: -4 },
                instruction: 'You’ve reached Junction Level 1. You may continue exploring or select the next route.',
            },
  ],
};
